{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"goodreads_works\",\"goodreads_reviews\",\"_Measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3ecfbe3c-984f-8f4d-f80a-fb50d6f60fc0",
        "fromColumn": "original_publication_year",
        "fromTable": "goodreads_works",
        "toColumn": "Year",
        "toTable": "Year"
      },
      {
        "name": "d0bb84cb-7794-f3b2-ab0f-b5628014823e",
        "fromColumn": "Genre",
        "fromTable": "BooksGenres",
        "toColumn": "Genres",
        "toTable": "Genre"
      },
      {
        "name": "246913b2-11fb-758b-914f-25aac2dba1fa",
        "fromColumn": "work_id",
        "fromTable": "goodreads_reviews",
        "toColumn": "work_id",
        "toTable": "goodreads_works"
      },
      {
        "name": "cb6ed601-e81d-40e1-95d1-595f85df02ff",
        "fromColumn": "workid",
        "fromTable": "BooksGenres",
        "toColumn": "work_id",
        "toTable": "goodreads_works"
      },
      {
        "name": "921d70eb-3bfd-281e-7ced-8cb05fd74327",
        "fromColumn": "Parentid",
        "fromTable": "SimilarBooks",
        "toColumn": "work_id",
        "toTable": "goodreads_works"
      },
      {
        "name": "c5db785d-b4ee-036b-a521-95d9593a5e9c",
        "fromColumn": "work_id",
        "fromTable": "SimilarBooks",
        "isActive": false,
        "toColumn": "work_id",
        "toTable": "goodreads_works"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "goodreads_works",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "work_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea405a52-8caf-4b44-ae25-1d3f1368d767",
            "sourceColumn": "work_id",
            "summarizeBy": "none"
          },
          {
            "name": "isbn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c3ebd8c-1112-40a1-b0fb-e3f586daf482",
            "sourceColumn": "isbn",
            "summarizeBy": "none"
          },
          {
            "name": "isbn13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c615cc1a-00a1-4c59-b121-df8d511897c0",
            "sourceColumn": "isbn13",
            "summarizeBy": "none"
          },
          {
            "name": "original_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54f6f785-5bca-4c65-9684-7405ef982ec5",
            "sourceColumn": "original_title",
            "summarizeBy": "none"
          },
          {
            "name": "author",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72460546-e572-4c82-8713-4148e2fd8a0f",
            "sourceColumn": "author",
            "summarizeBy": "none"
          },
          {
            "name": "original_publication_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fa3d9c9-5a22-4731-b2e2-a71af68cfd92",
            "sourceColumn": "original_publication_year",
            "summarizeBy": "none"
          },
          {
            "name": "num_pages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3e9c174-f72f-404a-9928-0ad1a4e0c717",
            "sourceColumn": "num_pages",
            "summarizeBy": "sum"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6bd9302-d4ed-4908-9939-629c9815703c",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "genres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3675ec67-89cd-4967-9505-34d3d4267a7f",
            "sourceColumn": "genres",
            "summarizeBy": "none"
          },
          {
            "name": "image_url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "290ebad4-563a-4afc-9871-3b97ad887532",
            "sourceColumn": "image_url",
            "summarizeBy": "none"
          },
          {
            "name": "reviews_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05df9cf5-c932-4b2d-af07-5038afbf4349",
            "sourceColumn": "reviews_count",
            "summarizeBy": "none"
          },
          {
            "name": "text_reviews_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b046dfe6-57a6-4897-ae3e-d347efcadc94",
            "sourceColumn": "text_reviews_count",
            "summarizeBy": "sum"
          },
          {
            "name": "5_star_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "63edac28-9434-4d85-bcfe-ae8c32f2d0e0",
            "sourceColumn": "5_star_ratings",
            "summarizeBy": "sum"
          },
          {
            "name": "4_star_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8cc15e7e-b6d6-48cc-9f6e-318849a2f681",
            "sourceColumn": "4_star_ratings",
            "summarizeBy": "sum"
          },
          {
            "name": "3_star_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "38164509-807b-4c07-8641-3a5cf553376c",
            "sourceColumn": "3_star_ratings",
            "summarizeBy": "sum"
          },
          {
            "name": "2_star_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bcea5481-7b17-43ab-9378-a4cde11d88d9",
            "sourceColumn": "2_star_ratings",
            "summarizeBy": "sum"
          },
          {
            "name": "1_star_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cade0ad1-be5d-46f8-974c-5caa5628db3c",
            "sourceColumn": "1_star_ratings",
            "summarizeBy": "sum"
          },
          {
            "name": "ratings_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11a00c7d-ce5b-4afd-9769-a126bf0f2f17",
            "sourceColumn": "ratings_count",
            "summarizeBy": "sum"
          },
          {
            "name": "avg_rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78c73ba7-73a1-4d89-a0f7-4591c45c3e3c",
            "sourceColumn": "avg_rating",
            "summarizeBy": "sum"
          },
          {
            "name": "similar_books",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53e9f9e5-376d-41be-8429-0038c10ef37c",
            "sourceColumn": "similar_books",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0be068ee-1c68-4005-8f66-39898576e56e",
        "partitions": [
          {
            "name": "goodreads_works",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\NAIRA1\\OneDrive - Community Health Choice\\Documents\\PowerBI\\GoodReads\\Goodreads+Book+Reviews\\goodreads_works.csv\"),[Delimiter=\",\", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Promoted Headers\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"avg_rating\", type number}, {\"text_reviews_count\", Int64.Type}, {\"5_star_ratings\", Int64.Type}, {\"4_star_ratings\", Int64.Type}, {\"3_star_ratings\", Int64.Type}, {\"1_star_ratings\", Int64.Type}, {\"2_star_ratings\", Int64.Type}, {\"ratings_count\", Int64.Type}, {\"num_pages\", Int64.Type}, {\"original_publication_year\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "goodreads_reviews",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "review_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08504132-5046-4fa1-8a87-34f7201991d2",
            "sourceColumn": "review_id",
            "summarizeBy": "none"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efb4e473-45d3-418d-99c2-b26dfce4e7c1",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "work_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "084cf63d-00b5-4116-8cd7-125ae68e1a11",
            "sourceColumn": "work_id",
            "summarizeBy": "none"
          },
          {
            "name": "started_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aad06ead-cfa2-4012-9cbe-e1cc6e8226c6",
            "sourceColumn": "started_at",
            "summarizeBy": "none"
          },
          {
            "name": "read_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a2bc534-9522-49eb-b3b3-c8ec3476a816",
            "sourceColumn": "read_at",
            "summarizeBy": "none"
          },
          {
            "name": "date_added",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "e6363b2b-7e5e-41de-867a-aef1954c894b",
            "sourceColumn": "date_added",
            "summarizeBy": "none"
          },
          {
            "name": "rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40c51ea2-822f-479d-9070-65d3ac26d449",
            "sourceColumn": "rating",
            "summarizeBy": "sum"
          },
          {
            "name": "review_text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dce661e3-be7d-4663-a9f0-73ce793ba220",
            "sourceColumn": "review_text",
            "summarizeBy": "none"
          },
          {
            "name": "n_votes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e970cc3c-270a-44b5-8330-41fcd995789c",
            "sourceColumn": "n_votes",
            "summarizeBy": "sum"
          },
          {
            "name": "n_comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d49a4374-5c2d-46e6-9c24-12e789fcab27",
            "sourceColumn": "n_comments",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3e22d5ca-4f35-4d09-bbe1-3a3f5b0a2094",
        "partitions": [
          {
            "name": "goodreads_reviews",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\NAIRA1\\OneDrive - Community Health Choice\\Documents\\PowerBI\\GoodReads\\Goodreads+Book+Reviews\\goodreads_reviews.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"review_id\", type text}, {\"user_id\", type text}, {\"work_id\", Int64.Type}, {\"started_at\", type text}, {\"read_at\", type text}, {\"date_added\", type datetime}, {\"rating\", Int64.Type}, {\"review_text\", type text}, {\"n_votes\", Int64.Type}, {\"n_comments\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "09d805b4-27fb-4a56-94c9-e0eefefebe09",
        "measures": [
          {
            "name": "Count_Books",
            "expression": [
              "",
              "DISTINCTCOUNT((goodreads_works[isbn]))"
            ],
            "formatString": "0",
            "lineageTag": "87e27479-8e38-4a56-9730-04a6c6411737"
          },
          {
            "name": "Book Details",
            "expression": [
              "",
              "VAR BookTitle = SELECTEDVALUE(goodreads_works[original_title])",
              "VAR BookAuthor = SELECTEDVALUE(goodreads_works[author])",
              "VAR PublicationYear = SELECTEDVALUE(goodreads_works[original_publication_year])",
              "VAR BookGenre = SELECTEDVALUE(goodreads_works[genres])",
              "RETURN",
              "    BookTitle & UNICHAR(10) & UNICHAR(10) & \" by \"  & BookAuthor & UNICHAR(10) & UNICHAR(10) & \"Published in \" &  PublicationYear & UNICHAR(10) & UNICHAR(10) & \"Genre: \"  & BookGenre",
              ""
            ],
            "lineageTag": "6ec7e9ba-e5d2-487a-a8ac-c4ad047d1840"
          },
          {
            "name": "Star Rating",
            "expression": [
              "",
              "VAR MaxStars = 5 // Define the maximum number of stars (e.g., 5)",
              "VAR CurrentRating = AVERAGE(goodreads_works[avg_rating]) // Replace with your actual table and rating column",
              "",
              "VAR FullStars = INT(CurrentRating) // Integer part for filled stars",
              "VAR HalfStar = IF(CurrentRating - FullStars >= 0.5, UNICHAR(9734), \"\") // Optional: For half-star representation",
              "VAR EmptyStars = MaxStars - FullStars - IF(HalfStar <> \"\", 1, 0) // Remaining empty stars",
              "",
              "RETURN",
              " ",
              "    REPT(UNICHAR(128970), FullStars) & HalfStar & REPT(UNICHAR(9734), EmptyStars)"
            ],
            "lineageTag": "996f32d3-fa73-430e-89fc-175e107c6207"
          },
          {
            "name": "Facts",
            "expression": [
              "",
              "\"Oldest book\" &",
              "\"Maximum number of pages\" &",
              "\"MAximum reviews\" &",
              "\"MAximum ratings count\" &",
              "\"Rating Count\" &",
              "\"Author with most books\"&",
              "\"Gener with most books\" &",
              "\"Most books publsihed year\""
            ],
            "lineageTag": "2ee44d4a-781b-446c-bee1-d20ed394e3fc"
          },
          {
            "name": "FilteredByGenre",
            "expression": [
              "",
              "VAR SelectedGenre = SELECTEDVALUE(Genre[Genres])",
              "",
              "RETURN",
              "    IF (",
              "        ISBLANK ( SelectedGenre ) || CONTAINSSTRING ( MAX(goodreads_works[genres]), SelectedGenre ) ,",
              "        1,",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1c5414d8-fc69-4ad7-b556-b29fcc5cbeb2"
          },
          {
            "name": "Book with Max Pages and Author",
            "expression": [
              "",
              "",
              "",
              "",
              "",
              "VAR MaxPagesValue = MAXX ( ALL ( goodreads_works ), goodreads_works[num_pages] )",
              "VAR MaxPageBookDetails =",
              "    TOPN (",
              "        1,",
              "        FILTER (",
              "            ALL ( goodreads_works ),",
              "            goodreads_works[num_pages] = MaxPagesValue",
              "        ),",
              "        goodreads_works[original_title], ASC,",
              "        goodreads_works[Author], ASC",
              "    )",
              "RETURN",
              "    CONCATENATEX (",
              "        MaxPageBookDetails,",
              "         UNICHAR(10025) & \" \" &goodreads_works[original_title] & \" by \" & goodreads_works[Author] & \" (Pages: \" & goodreads_works[num_pages] & \") has most number of pages.\",",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "711f1bc5-7a86-407c-9e87-05323d87106d"
          },
          {
            "name": "Book with Max Rating Count",
            "expression": [
              "",
              "",
              "VAR MaxRatingCount = MAXX ( ALL ( goodreads_works ), goodreads_works[ratings_count] )",
              "VAR BookDetails =",
              "    TOPN (",
              "        1,",
              "        FILTER (",
              "            ALL ( goodreads_works ),",
              "            goodreads_works[ratings_count] = MaxRatingCount",
              "        ),",
              "        goodreads_works[original_title], ASC,",
              "        goodreads_works[Author], ASC",
              "    )",
              "RETURN",
              "    CONCATENATEX (",
              "        BookDetails,",
              "         UNICHAR(10025) & \" \" & goodreads_works[original_title] & \" is the book with the most rating count (Ratings: \" & goodreads_works[ratings_count] & \")\",",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "1941cc85-82e8-4a55-93b9-504fb62c67b3"
          },
          {
            "name": "Author with Most Books",
            "expression": [
              "",
              "VAR AuthorBookCounts =",
              "    SUMMARIZE (",
              "        goodreads_works,",
              "        goodreads_works[Author],",
              "        \"BookCount\", COUNT ( goodreads_works[original_title] )",
              "    )",
              "VAR _Author=",
              "    MAXX (",
              "        TOPN ( 1, AuthorBookCounts, [BookCount] ),",
              "        goodreads_works[Author]",
              "    )",
              "RETURN ",
              "  UNICHAR(10025) & \" \" & _Author & \" has the most number of books.\"",
              "",
              ""
            ],
            "lineageTag": "85e5eed6-bf0f-4dc5-8737-7e22662078cf"
          },
          {
            "name": "Year with Most Books Published",
            "expression": [
              "",
              "VAR BooksPerYear =",
              "    SUMMARIZE (",
              "        goodreads_works,",
              "        goodreads_works[original_publication_year],",
              "        \"BookCount\", COUNT ( goodreads_works[original_title] )",
              "    )",
              "VAR _Year=",
              "    MAXX (",
              "        TOPN ( 1, BooksPerYear, [BookCount] ),",
              "        goodreads_works[original_publication_year]",
              "    )",
              "RETURN ",
              " UNICHAR(10025) & \" Most of the books published in our catalog is from \" & _Year "
            ],
            "lineageTag": "07b74be6-93eb-418f-9305-c31076395bb5"
          },
          {
            "name": "Books per Genre",
            "expression": "COUNTROWS(BooksGenres)",
            "formatString": "0",
            "lineageTag": "1a0a855f-e101-42c2-a265-d870e7d7b18c"
          },
          {
            "name": "Genre with most books",
            "expression": [
              "",
              "VAR _Genre = MAX(BooksGenres[Genre])",
              "VAR _Genre_Capitalized=  IF (",
              "        NOT ISBLANK ( _Genre ),",
              "        UPPER ( LEFT ( _Genre, 1 ) ) & LOWER ( RIGHT ( _Genre, LEN ( _Genre ) - 1 ) ),",
              "        BLANK ()",
              "    )",
              "RETURN ",
              " UNICHAR(10025) & \" \" & _Genre_Capitalized & \" has the most number of books( \" & [Books per Genre] & \").\""
            ],
            "lineageTag": "bbb94123-4760-485d-93fc-ecf6b509da2f"
          },
          {
            "name": "Oldest Published Book Title and Author",
            "expression": [
              "",
              "VAR OldestPublishYear = CALCULATE(MIN(goodreads_works[original_publication_year]), ALL(goodreads_works))",
              "VAR OldestBookDetails =",
              "    TOPN(",
              "        1,",
              "        FILTER(",
              "            ALL(goodreads_works),",
              "            goodreads_works[original_publication_year] = OldestPublishYear",
              "        ),",
              "        goodreads_works[original_title], ASC,",
              "        goodreads_works[Author], ASC",
              "    )",
              "RETURN",
              "    CONCATENATEX(",
              "        OldestBookDetails,",
              "         UNICHAR(10025) & \" The oldest book in our collection is \" & goodreads_works[original_title] & \" by \" & goodreads_works[Author] & \" published in \" & goodreads_works[original_publication_year] &\".\",",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "9c20fc38-055e-4795-a5ae-1dcc0a254271"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SimilarBooks",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "56cd99b79d5d4e1d81121c29cdfa20e8"
          }
        ],
        "columns": [
          {
            "name": "original_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    LOOKUPVALUE(",
              "   goodreads_works[original_title], ",
              "   goodreads_works[work_id],",
              "   SimilarBooks[work_id]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "344b9ed4-1cfb-451b-af88-37512640e867",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Author",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "LOOKUPVALUE(",
              "   goodreads_works[author], ",
              "   goodreads_works[work_id],",
              "   SimilarBooks[work_id]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ed2f1f0e-18d6-4d73-bb57-2e37965a94f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "AverageRatings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "LOOKUPVALUE(",
              "   goodreads_works[avg_rating], ",
              "   goodreads_works[work_id],",
              "   SimilarBooks[work_id]",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "20c9eb16-5944-4f04-b767-c203726ff278",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Parentid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "74e2be84-742f-447a-bb92-48b733ac4120",
            "sourceColumn": "[Parentid]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "work_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4628a37b-1fcd-4167-ae50-dc55a27e9fc3",
            "sourceColumn": "[work_id]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "37706047-7a45-4202-ad90-e5e76b5d69b2",
        "partitions": [
          {
            "name": "SimilarBooks",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _PathItem = ADDCOLUMNS(",
                "    goodreads_works",
                "    ,\"Path Items\",SUBSTITUTE(goodreads_works[similar_books],\",\",\"|\")",
                ")",
                "",
                "",
                "VAR _PathLength = ADDCOLUMNS(_PathItem,\"PathLength\",PATHLENGTH([Path Items]))",
                "",
                "VAR MaxLength = MAXX(_PathLength,[PathLength])",
                "",
                "VAR _Series = GENERATESERIES(1,MaxLength,1)",
                "VAR _CrossJoined = CROSSJOIN(_PathItem,_Series)",
                "VAR _Items = ADDCOLUMNS(_CrossJoined,\"Items\",PATHITEM([Path Items],[Value]))",
                "//VAR _Items_Filtered = FILTER(_Items,NOT(ISBLANK( [Items]) && [Items] <> \"\" && [Items] <> \" \"))",
                "RETURN ",
                "SELECTCOLUMNS(FILTER(_Items,[Items] <> BLANK()",
                "              ",
                "              )",
                "              ,\"Parentid\",[work_id]",
                "             // ,\"Title\",[original_title]",
                "             //,\"Author\",[author]",
                "             //,\"ISBN13\",[isbn13]",
                "             //,\"ISBN\",[isbn]",
                "             ,\"work_id\",TRIM([Items])",
                "        ",
                "             )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Genre",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dd56ef3eaa024e0380235c956c539262"
          }
        ],
        "columns": [
          {
            "name": "Genres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0ea29559-974e-4be3-8511-012780405093",
            "sourceColumn": "[Genres]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d481e105-16bc-4d78-86b6-6ac06a2b32b1",
        "partitions": [
          {
            "name": "Genre",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _PathItem =",
                "                ADDCOLUMNS(",
                "                    goodreads_works",
                "                    ,\"Path Items\", SUBSTITUTE(goodreads_works[genres],\",\",\"|\")",
                "                )",
                "",
                "VAR _PathLength= ADDCOLUMNS(_PathItem,\"PathLength\",PATHLENGTH([Path Items]))    ",
                "",
                "VAR MAXLength = MAXX(_PathLength,[PathLength])",
                "",
                "VAR _Series =GENERATESERIES(1,MAXLength,1)",
                "",
                "VAR _CrossJoined = CROSSJOIN(_PathItem,_Series)",
                "VAR _Items = ADDCOLUMNS(_CrossJoined,\"Items\",PATHITEM([Path Items],[Value]))",
                "",
                "VAR GenreTable =DISTINCT(SELECTCOLUMNS(FILTER(_Items,NOT(ISBLANK( [Items]) && [Items] <> \" \")",
                "              ",
                "              )",
                "             ,\"Genres\",TRIM([Items])",
                "             ))",
                "RETURN ",
                "    GenreTable"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "BooksGenres",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "14fda46a83c04e36945a4f1c0d992b59"
          }
        ],
        "columns": [
          {
            "name": "workid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bb8b3b58-3d6a-4618-b261-d72bb94cee44",
            "sourceColumn": "[workid]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4f9de8e6-8b45-49b1-a25a-128a220d565d",
            "sourceColumn": "[Title]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Author",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a7ae94e7-051c-468d-a986-dd75909a89f8",
            "sourceColumn": "[Author]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ISBN13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "33cedee7-69d2-4945-b795-b219f9832c6c",
            "sourceColumn": "[ISBN13]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ISBN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "406346df-b898-4178-86fa-070b7fcc595e",
            "sourceColumn": "[ISBN]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Genre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "833a76ed-9220-4c21-8e94-4416fb465dd0",
            "sourceColumn": "[Genre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Average Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cf59c7f2-09e3-46c5-99ce-bfebfd9701e2",
            "sourceColumn": "[Average Rating]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RatingsCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0503fb74-8d3d-481b-917d-1bb90b1362f1",
            "sourceColumn": "[RatingsCount]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rank by Rating & Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "RANKX(",
              "    FILTER(",
              "        ALL(BooksGenres), ",
              "        BooksGenres[Genre]= EARLIER(BooksGenres[Genre]) ",
              "    ),",
              "    BooksGenres[Average Rating] * 0.7 + BooksGenres[RatingsCount] * 0.3, // Adjust weights as needed",
              "    , ",
              "    DESC, ",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bbd39619-517c-40ae-9694-6d656a447698",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bfe6540a-0395-4fa7-a840-0c38cf27d29a",
            "sourceColumn": "[Image]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1d6a723a-b248-4f75-a8d2-82bac7c75997",
        "partitions": [
          {
            "name": "BooksGenres",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _PathItem = ADDCOLUMNS(",
                "    goodreads_works",
                "    ,\"Path Items\",SUBSTITUTE(goodreads_works[genres],\",\",\"|\")",
                ")",
                "",
                "",
                "VAR _PathLength = ADDCOLUMNS(_PathItem,\"PathLength\",PATHLENGTH([Path Items]))",
                "",
                "VAR MaxLength = MAXX(_PathLength,[PathLength])",
                "",
                "VAR _Series = GENERATESERIES(1,MaxLength,1)",
                "VAR _CrossJoined = CROSSJOIN(_PathItem,_Series)",
                "VAR _Items = ADDCOLUMNS(_CrossJoined,\"Items\",PATHITEM([Path Items],[Value]))",
                "//VAR _Items_Filtered = FILTER(_Items,NOT(ISBLANK( [Items]) && [Items] <> \"\" && [Items] <> \" \"))",
                "VAR _BookGenres= ",
                "SELECTCOLUMNS(FILTER(_Items,[Items] <> BLANK()",
                "              ",
                "              )",
                "              ,\"workid\",[work_id]",
                "              ,\"Title\",[original_title]",
                "             ,\"Author\",[author]",
                "             ,\"ISBN13\",[isbn13]",
                "             ,\"ISBN\",[isbn]",
                "             ,\"Average Rating\",[avg_rating]",
                "             ,\"RatingsCount\",[ratings_count]",
                "             ,\"Image\",[image_url]",
                "             ,\"Genre\",TRIM([Items])",
                "             )",
                "",
                "",
                "",
                " RETURN _BookGenres"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Year",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cff434d3373044cb88e374c293e86ba2"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4645e5b1-c255-4259-8611-5a20ae4504f6",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "64bda076-549c-4514-b941-ba900b76bab5",
        "partitions": [
          {
            "name": "Year",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT (",
                "    SELECTCOLUMNS (",
                "        CALENDAR ( DATE ( 1008, 1, 1 ), TODAY () ),",
                "        \"Year\", YEAR ( [Date] )",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}